# Site settings
title: "Piotr Gryko"
email: piotr.gryko@gmail.com
description: "Little description"
baseurl: ""
url: "https://piotrgryko.co.uk"
title_description: "Developer with an interest in cryptocurrencies. I've built projects using
python, c++, ansible, vagrant."
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: ""
github_repository: https://gitlab.com/pgryko/
gitlab_repository: https://github.com/pgryko/
addthis_id: ra-513c6fa832323
email: piotr.gryko@gmail.com
post_limit: 5

# Social usernames/URLs
github_username:  pgryko
gitlab_username: pgryko
linkedin_link: https://www.linkedin.com/in/piotr-gryko-7bb43725/

# Footer
footer_left: "Got a suggestion or seen a typo?"
footer_right: "Submit a pull request on <a href=\"https://gitlab.com/pgryko/piotr-gryko\">Gitlab</a> &nbsp;<i class=\"fa fa-gitlab\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
